const BAD_REQ_ERR_CODE = 400;
const UNFRZ_ERR_CODE = 401;
const FRBDN_ERR_CODE = 403;
const NOT_FND_ERR_CODE = 404;
const CNFL_ERR_CODE = 409;
const SERV_ERR_CODE = 500;

module.exports = {
  BAD_REQ_ERR_CODE, NOT_FND_ERR_CODE, SERV_ERR_CODE, FRBDN_ERR_CODE, CNFL_ERR_CODE, UNFRZ_ERR_CODE,
};
